export const GET_SONGS = 'GET_SONGS'
export const RECIEVED_GET_SONGS = 'RECIEVED_GET_SONGS'
export const FAILURE_GET_SONGS = 'FAILURE_GET_SONGS'

export const CREATE_SONG = 'CREATE_SONG'
export const RECIEVED_NEW_SONG = 'RECIEVED_NEW_SONG'
export const FAILURE_CREATE_SONG = 'FAILURE_CREATE_SONG'


export const GET_GENRES = 'GET_GENRES'
export const RECIEVED_GET_GENRES = 'RECIEVED_GET_GENRES'
export const FAILURE_GET_GENRES = 'FAILURE_GET_GENRES'